name = "api-market-x402"
main = "src/index.ts"
compatibility_date = "2024-12-01"

assets = { directory = "dist", binding = "ASSETS", not_found_handling = "single-page-application" }

routes = [
  { pattern = "api-402.com/*", zone_name = "api-402.com" }
]

[vars]
APP_NAME = "API Market"
